# Generated by Django 4.0.2 on 2022-06-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0002_harga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harga',
            old_name='komoditas_id',
            new_name='komoditas',
        ),
    ]
