# Generated by Django 4.0.2 on 2022-11-17 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0007_alter_harga_komoditas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model', models.CharField(max_length=10)),
                ('start_train', models.DateField()),
                ('end_train', models.DateField()),
                ('start_ramal', models.DateField()),
                ('end_ramal', models.DateField()),
                ('komoditas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bahanpokok.komoditas')),
            ],
        ),
        migrations.CreateModel(
            name='DetailRamal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('harga', models.IntegerField()),
                ('ramal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bahanpokok.ramal')),
            ],
        ),
    ]
