# Generated by Django 4.0.2 on 2022-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0008_ramal_detailramal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
