# Generated by Django 4.0.2 on 2022-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0009_alter_ramal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailramal',
            name='harga',
            field=models.FloatField(),
        ),
    ]
