# Generated by Django 4.0.2 on 2022-11-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0010_alter_detailramal_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
