# Generated by Django 4.0.2 on 2022-11-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0011_alter_ramal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailramal',
            old_name='harga',
            new_name='aktual',
        ),
        migrations.AlterField(
            model_name='detailramal',
            name='ramal',
            field=models.FloatField(),
        ),
    ]
