# Generated by Django 4.0.2 on 2022-11-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0012_rename_harga_detailramal_aktual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailramal',
            old_name='aktual',
            new_name='harga_aktual',
        ),
        migrations.AddField(
            model_name='detailramal',
            name='harga_ramal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ramal',
            name='mape_ramal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ramal',
            name='rmse_ramal',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailramal',
            name='ramal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bahanpokok.ramal'),
        ),
    ]
