# Generated by Django 4.0.2 on 2022-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0013_rename_aktual_detailramal_harga_aktual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailramal',
            name='harga_aktual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detailramal',
            name='harga_ramal',
            field=models.FloatField(null=True),
        ),
    ]
