# Generated by Django 4.0.2 on 2022-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahanpokok', '0014_alter_detailramal_harga_aktual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='mape_ramal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='rmse_ramal',
            field=models.FloatField(null=True),
        ),
    ]
